---
- name: Verify Azure Hub-and-Spoke DNS Server
  hosts: all
  gather_facts: false

  tasks:
    - name: Gathering Network Facts
      setup:
        gather_subset:
          - 'network'

    - name: Set local DNS resolver target
      set_fact:
        local_dns: "{{ '@' + ansible_default_ipv4.address }}"

    - name: Verify Azure Private Domain Lookups (.internal)
      assert:
        that:
          - lookup('dig', 'bastion.internal', local_dns) == '10.0.0.4'
          - lookup('dig', 'awx1.internal', local_dns)    == '10.1.1.5'
          - lookup('dig', 'awx2.internal', local_dns)    == '10.1.1.4'

    - name: Verify Azure PTR Reverse DNS Lookups
      assert:
        that:
          - lookup('dig', '10.0.0.4/PTR', local_dns) == 'bastion.internal.'
          - lookup('dig', '10.1.1.5/PTR', local_dns) == 'awx1.internal.'
          - lookup('dig', '10.1.1.4/PTR', local_dns) == 'awx2.internal.'

    - name: Verify Outbound Recursive DNS Forwarding (Azure / Google)
      assert:
        that:
          - lookup('dig', 'packages.microsoft.com', local_dns) != ''
